---
- name: Oracle Open Ports
  hosts: oracle-all
  gather_facts: yes
  become: yes

  tasks:
   - name: Allow connections on multiple ports
     ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_ports:
          - "80"
          - "443"
        jump: ACCEPT

